# Generated by Django 5.2.3 on 2025-07-09 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="اسم المجموعة")),
            ],
            options={
                "verbose_name": "مجموعة",
                "verbose_name_plural": "المجموعات",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم الكامل")),
                (
                    "phone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(auto_now_add=True, verbose_name="تاريخ التسجيل"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.group",
                        verbose_name="المجموعة",
                    ),
                ),
            ],
            options={
                "verbose_name": "طالب",
                "verbose_name_plural": "الطلاب",
            },
        ),
    ]
