# Generated by Django 5.2.3 on 2025-07-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(
                default="", max_length=128, verbose_name="كلمة المرور"
            ),
            preserve_default=False,
        ),
    ]
