# Generated by Django 5.2.3 on 2025-07-09 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                ("attendance", models.BooleanField(default=False, verbose_name="حضور")),
                (
                    "grade",
                    models.FloatField(blank=True, null=True, verbose_name="الدرجة"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="students.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل أسبوعي",
                "verbose_name_plural": "السجلات الأسبوعية",
                "ordering": ["-date"],
            },
        ),
    ]
